version: '3.8'

services:

  loadbalancer:
    image: ghcr.io/silkkycloud/traefik:2.6.0
    command: --configFile=/etc/traefik/traefik.yml
    cap_add:
      # Image runs rootless, This allows Docker to bind the privileged ports
      - NET_BIND_SERVICE
    hostname: cockroach-lb
    networks:
      - cockroachdb_net
    deploy:
      mode: replicated
      replicas: 3
      placement:
        constraints:
          - "node.labels.web_server == true"
      update_config:
        parallelism: 1
        failure_action: rollback
      resources:
        reservations:
          memory: 25M
          cpus: '0.05'
        limits:
          memory: 150M
          cpus: '0.1'
    configs:
      - source: traefik-static
        target: /etc/traefik/traefik.yml
        uid: "1000"
        gid: "1000"
      - source: traefik-dynamic
        target: /etc/traefik/dynamic.yml
        uid: "1000"
        gid: "1000"

  db-1:
    image: cockroachdb/cockroach:v21.2.7
    command: start --join=cockroachdb-1:26257,cockroachdb-2:26257,cockroachdb-3:26257 --cache=.25 --max-sql-memory=.25 --logtostderr --certs-dir=/run/secrets --accept-sql-without-tls
    hostname: cockroachdb-1
    networks:
      - public
      - metrics_net
      - cockroachdb_net
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - "node.hostname == main.web01.hel.hcloud.silkky.cloud"
      update_config:
        failure_action: rollback
        delay: 10s
      resources:
        limits:
          cpus: '2'
          memory: 5G
        reservations:
          cpus: '0.3'
          memory: 2G
      labels:
        # Prometheus
        - "prometheus-job=cockroachdb"
        - "prometheus-port=8080"
        - "prometheus-path=/_status/vars"
    volumes:
      - database-1:/cockroach/cockroach-data
      # Fix time sync issue
      - /etc/localtime:/etc/localtime:ro
    secrets:
      # CA certificate
      - source: cockroach-ca-crt
        target: ca.crt
      # Node certificate
      - source: cockroachdb-1-crt
        target: node.crt
      # Node key
      - source: cockroachdb-1-key
        target: node.key
        mode: 0600
      # Root certificate
      - source: cockroach-root-crt
        target: client.root.crt
      # Root key
      - source: cockroach-root-key
        target: client.root.key
        mode: 0600

  db-2:
    image: cockroachdb/cockroach:v21.2.7
    command: start --join=cockroachdb-1:26257,cockroachdb-2:26257,cockroachdb-3:26257 --cache=.25 --max-sql-memory=.25 --logtostderr --certs-dir=/run/secrets --accept-sql-without-tls
    hostname: cockroachdb-2
    networks:
      - metrics_net
      - cockroachdb_net
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - "node.hostname == main.web02.hel.hcloud.silkky.cloud"
      update_config:
        failure_action: rollback
        delay: 10s
      resources:
        limits:
          cpus: '2'
          memory: 5G
        reservations:
          cpus: '0.3'
          memory: 2G
      labels:
        # Prometheus
        - "prometheus-job=cockroachdb"
        - "prometheus-port=8080"
        - "prometheus-path=/_status/vars"
    volumes:
      - database-2:/cockroach/cockroach-data
      # Fix time sync issue
      - /etc/localtime:/etc/localtime:ro
    secrets:
      # CA certificate
      - source: cockroach-ca-crt
        target: ca.crt
      # Node certificate
      - source: cockroachdb-2-crt
        target: node.crt
      # Node key
      - source: cockroachdb-2-key
        target: node.key
        mode: 0600
      # Root certificate
      - source: cockroach-root-crt
        target: client.root.crt
      # Root key
      - source: cockroach-root-key
        target: client.root.key
        mode: 0600

  db-3:
    image: cockroachdb/cockroach:v21.2.4
    command: start --join=cockroachdb-1:26257,cockroachdb-2:26257,cockroachdb-3:26257 --cache=.25 --max-sql-memory=.25 --logtostderr --certs-dir=/run/secrets --accept-sql-without-tls
    hostname: cockroachdb-3
    networks:
      - metrics_net
      - cockroachdb_net
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - "node.hostname == main.web03.hel.hcloud.silkky.cloud"
      update_config:
        failure_action: rollback
        delay: 10s
      resources:
        limits:
          cpus: '2'
          memory: 5G
        reservations:
          cpus: '0.3'
          memory: 2G
      labels:
        # Prometheus
        - "prometheus-job=cockroachdb"
        - "prometheus-port=8080"
        - "prometheus-path=/_status/vars"
    volumes:
      - database-3:/cockroach/cockroach-data
      # Fix time sync issue
      - /etc/localtime:/etc/localtime:ro
    secrets:
      # CA certificate
      - source: cockroach-ca-crt
        target: ca.crt
      # Node certificate
      - source: cockroachdb-3-crt
        target: node.crt
      # Node key
      - source: cockroachdb-3-key
        target: node.key
        mode: 0600
      # Root certificate
      - source: cockroach-root-crt
        target: client.root.crt
      # Root key
      - source: cockroach-root-key
        target: client.root.key
        mode: 0600

  # Simple file server for hosting database dump files
  importer:
    image: ghcr.io/silkkycloud/cockroach-importer:latest
    hostname: cockroach-importer
    networks:
      - cockroachdb_net
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - "node.hostname == main.web01.hel.hcloud.silkky.cloud"
      update_config:
        order: start-first
      resources:
        reservations:
          memory: 5M
          cpus: '0.05'
        limits:
          memory: 100M
          cpus: '0.1'
    volumes:
      - importer_data:/srv

networks:
  # Create:
  # docker network create \
  #   --driver overlay \ 
  #   --attachable \
  #   --opt com.docker.network.driver.mtu=1450 \ # IF USING HETZNER CLOUD NETS
  #   --opt encrypted=true \
  #   cockroachdb_net
  cockroachdb_net:
    external: true
  # Collect Prometheus metrics
  metrics_net:
    external: true
  public:
    external: true

volumes:
  database-1:
  database-2:
  database-3:
  importer_data:

configs:
  traefik-static:
    file: ./traefik/traefik.yml
  traefik-dynamic:
    file: ./traefik/dynamic.yml

secrets:
  # CA certificate
  cockroach-ca-crt:
    external: true
  # Node certificates
  cockroachdb-1-crt:
    external: true
  cockroachdb-2-crt:
    external: true
  cockroachdb-3-crt:
    external: true
  # Node keys
  cockroachdb-1-key:
    external: true
  cockroachdb-2-key:
    external: true
  cockroachdb-3-key:
    external: true
  # Root certificate
  cockroach-root-crt:
    external: true
  cockroach-root-key:
    external: true