version: '3.8'

services:

  # Simple TCP LB for connecting to CockroachDB
  loadbalancer:
    image: haproxy:2.5-alpine
    hostname: cockroach-lb
    networks:
      - cockroachdb_net
    deploy:
      mode: replicated
      replicas: 3
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 10s
      resources:
        reservations:
          memory: 5M
          cpus: '0.05'
        limits:
          memory: 100M
          cpus: '0.1'
    configs:
      - source: haproxy_config
        target: /usr/local/etc/haproxy/haproxy.cfg

  db-1:
    image: cockroachdb/cockroach:v21.2.2
    command: start --join=cockroachdb-1:26257,cockroachdb-2:26257,cockroachdb-3:26257 --cache=.25 --max-sql-memory=.25 --logtostderr --certs-dir=/run/secrets
    hostname: cockroachdb-1
    networks:
      - cockroachdb_net
      - metrics_net
      - public
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - "node.hostname == main-1"
      update_config:
        failure_action: rollback
        delay: 10s
      resources:
        limits:
          cpus: '2'
          memory: 5G
        reservations:
          cpus: '0.3'
          memory: 2G
      labels:
        prometheus-job: cockroachdb-1
        prometheus-port: 8080
        prometheus-path: /_status/vars
    volumes:
      - database-1:/cockroach/cockroach-data
      # Fix time sync issue
      - /etc/localtime:/etc/localtime:ro
    secrets:
      # CA Certificate
      - source: cockroach-ca-crt
        target: ca.crt
      # Node Certificate
      - source: cockroachdb-1-crt
        target: node.crt
      # Node Key
      - source: cockroachdb-1-key
        target: node.key
        mode: 0600
      # Root Certificate
      - source: cockroach-root-crt
        target: client.root.crt
      # Root Key
      - source: cockroach-root-key
        target: client.root.key
        mode: 0600

  db-2:
    image: cockroachdb/cockroach:v21.2.2
    command: start --join=cockroachdb-1:26257,cockroachdb-2:26257,cockroachdb-3:26257 --cache=.25 --max-sql-memory=.25 --logtostderr --certs-dir=/run/secrets 
    hostname: cockroachdb-2
    networks:
      - cockroachdb_net
      - metrics_net
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - "node.hostname == main-2"
      update_config:
        failure_action: rollback
        delay: 10s
      resources:
        limits:
          cpus: '2'
          memory: 5G
        reservations:
          cpus: '0.3'
          memory: 2G
      labels:
        prometheus-job: cockroachdb-2
        prometheus-port: 8080
        prometheus-path: /_status/vars
    volumes:
      - database-2:/cockroach/cockroach-data
      # Fix time sync issue
      - /etc/localtime:/etc/localtime:ro
    secrets:
      # CA Certificate
      - source: cockroach-ca-crt
        target: ca.crt
      # Node Certificate
      - source: cockroachdb-2-crt
        target: node.crt
      # Node Key
      - source: cockroachdb-2-key
        target: node.key
        mode: 0600
      # Root Certificate
      - source: cockroach-root-crt
        target: client.root.crt
      # Root Key
      - source: cockroach-root-key
        target: client.root.key
        mode: 0600

  db-3:
    image: cockroachdb/cockroach:v21.2.2
    command: start --join=cockroachdb-1:26257,cockroachdb-2:26257,cockroachdb-3:26257 --cache=.25 --max-sql-memory=.25 --logtostderr --certs-dir=/run/secrets 
    hostname: cockroachdb-3
    networks:
      - cockroachdb_net
      - metrics_net
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - "node.hostname == main-3"
      update_config:
        failure_action: rollback
        delay: 10s
      resources:
        limits:
          cpus: '2'
          memory: 5G
        reservations:
          cpus: '0.3'
          memory: 2G
      labels:
        prometheus-job: cockroachdb-3
        prometheus-port: 8080
        prometheus-path: /_status/vars
    volumes:
      - database-3:/cockroach/cockroach-data
      # Fix time sync issue
      - /etc/localtime:/etc/localtime:ro
    secrets:
      # CA Certificate
      - source: cockroach-ca-crt
        target: ca.crt
      # Node Certificate
      - source: cockroachdb-3-crt
        target: node.crt
      # Node Key
      - source: cockroachdb-3-key
        target: node.key
        mode: 0600
      # Root Certificate
      - source: cockroach-root-crt
        target: client.root.crt
      # Root Key
      - source: cockroach-root-key
        target: client.root.key
        mode: 0600

networks:
  # Create:
  # docker network create \
  #   --driver overlay \ 
  #   --attachable \
  #   --opt com.docker.network.driver.mtu=1450 \ # IF USING HETZNER CLOUD NETS
  #   --opt encrypted=true \
  #   cockroachdb_net
  cockroachdb_net:
    external: true
  # Collect Prometheus metrics
  metrics_net:
    external: true

  public:
    external: true

volumes:
  database-1:
  database-2:
  database-3:

secrets:
  # CA Certificate
  cockroach-ca-crt:
    external: true
  # Node Certificates
  cockroachdb-1-crt:
    external: true
  cockroachdb-2-crt:
    external: true
  cockroachdb-3-crt:
    external: true
  # Node Keys
  cockroachdb-1-key:
    external: true
  cockroachdb-2-key:
    external: true
  cockroachdb-3-key:
    external: true
  # Root Certificate
  cockroach-root-crt:
    external: true
  # Root Key
  cockroach-root-key:
    external: true

configs:
  haproxy_config:
    file: ./haproxy.cfg