version: '3.8'

services:

  # Simple TCP LB for connecting to CockroachDB
  loadbalancer:
    image: haproxy:2.5-alpine
    hostname: cockroach-lb
    networks:
      - cockroachdb_net
    deploy:
      mode: replicated
      replicas: 3
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 10s
      resources:
        reservations:
          memory: 5M
          cpus: '0.05'
        limits:
          memory: 100M
          cpus: '0.1'
    configs:
      - source: haproxy_config
        target: /usr/local/etc/haproxy/haproxy.cfg

  db-1:
    image: cockroachdb/cockroach:v21.2.2
    # (--insecure) is ok because cluster is using private networking and encryption is supplied using IPSec
    command: start --join=cockroachdb-1:26257,cockroachdb-2:26257,cockroachdb-3:26257 --cache=.25 --max-sql-memory=.25 --logtostderr --insecure 
    hostname: cockroachdb-1
    networks:
      - public
      - metrics_net
      - cockroachdb_net
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - "node.hostname == main-1"
      update_config:
        failure_action: rollback
        delay: 10s
      resources:
        limits:
          cpus: '2'
          memory: 5G
        reservations:
          cpus: '0.3'
          memory: 2G
      labels:
        # Prometheus
        - "prometheus-job=cockroachdb"
        - "prometheus-port=8080"
        - "prometheus-path=/_status/vars"
        # Traefik
        - "traefik.enable=true"
        # Router
        - "traefik.http.routers.cockroachdb-admin.rule=Host(`${HOSTNAME}`)"
        - "traefik.http.routers.cockroachdb-admin.entrypoints=websecure"
        - "traefik.http.routers.cockroachdb-admin.tls=true"
        - "traefik.http.routers.cockroachdb-admin.middlewares=authelia@docker"
        - "traefik.http.routers.cockroachdb-admin.service=cockroachdb-admin-service"
        # Service
        - "traefik.http.services.cockroachdb-admin-service.loadbalancer.server.port=8080"
    volumes:
      - database-1:/cockroach/cockroach-data
      # Fix time sync issue
      - /etc/localtime:/etc/localtime:ro

  db-2:
    image: cockroachdb/cockroach:v21.2.2
    # (--insecure) is ok because cluster is using private networking and encryption is supplied using IPSec
    command: start --join=cockroachdb-1:26257,cockroachdb-2:26257,cockroachdb-3:26257 --cache=.25 --max-sql-memory=.25 --logtostderr --insecure 
    hostname: cockroachdb-2
    networks:
      - metrics_net
      - cockroachdb_net
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - "node.hostname == main-2"
      update_config:
        failure_action: rollback
        delay: 10s
      resources:
        limits:
          cpus: '2'
          memory: 5G
        reservations:
          cpus: '0.3'
          memory: 2G
      labels:
        # Prometheus
        - "prometheus-job=cockroachdb"
        - "prometheus-port=8080"
        - "prometheus-path=/_status/vars"
    volumes:
      - database-2:/cockroach/cockroach-data
      # Fix time sync issue
      - /etc/localtime:/etc/localtime:ro

  db-3:
    image: cockroachdb/cockroach:v21.2.2
    # (--insecure) is ok because cluster is using private networking and encryption is supplied using IPSec
    command: start --join=cockroachdb-1:26257,cockroachdb-2:26257,cockroachdb-3:26257 --cache=.25 --max-sql-memory=.25 --logtostderr --insecure 
    hostname: cockroachdb-3
    networks:
      - metrics_net
      - cockroachdb_net
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - "node.hostname == main-3"
      update_config:
        failure_action: rollback
        delay: 10s
      resources:
        limits:
          cpus: '2'
          memory: 5G
        reservations:
          cpus: '0.3'
          memory: 2G
      labels:
        # Prometheus
        - "prometheus-job=cockroachdb"
        - "prometheus-port=8080"
        - "prometheus-path=/_status/vars"
    volumes:
      - database-3:/cockroach/cockroach-data
      # Fix time sync issue
      - /etc/localtime:/etc/localtime:ro

  # Simple file server for hosting database dump files
  importer:
    image: caddy:2-alpine
    hostname: cockroach-importer
    networks:
      - cockroachdb_net
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - "node.hostname == main-1"
      update_config:
        order: start-first
      resources:
        reservations:
          memory: 5M
          cpus: '0.05'
        limits:
          memory: 100M
          cpus: '0.1'
    volumes:
      - importer_data:/srv
    configs:
      - source: importer_caddyfile
        target: /etc/caddy/Caddyfile

networks:
  # Create:
  # docker network create \
  #   --driver overlay \ 
  #   --attachable \
  #   --opt com.docker.network.driver.mtu=1450 \ # IF USING HETZNER CLOUD NETS
  #   --opt encrypted=true \
  #   cockroachdb_net
  cockroachdb_net:
    external: true
  # Collect Prometheus metrics
  metrics_net:
    external: true
  public:
    external: true

volumes:
  database-1:
  database-2:
  database-3:
  importer_data:

configs:
  haproxy_config:
    file: ./haproxy.cfg
  importer_caddyfile:
    file: ./Importer.Caddyfile